name: forgeops_smoke_test
description: Run smoke tests on a deployed ForgeOps platform
version: 0.0.1
homepage: https://github.com/ForgeRock/forgeops

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.0.0
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0
  dio: ^4.0.0-beta7
  dio_cookie_manager: ^2.0.0-beta1
#  http: ^0.12.1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8

